Numpy is a library for numerical math operations - matrixes and vectors mostly
The heart of Numpy data structure is Numpy array. It can represent vector (1D), matrixex (2D) or have more dimensions to represent more complex quantities. NumPy array allow ony one type to be stored. Thanks to specific type stored, numpy array can provide linear algebra operations
Linear equations look like: y = ax+b, where a and b are numbers

Model is a relationship between features - in form of math equation. By using a model you can predict specific feature of our reality

This is the concept of machine learning: create a model that represent relationship between diffrent variables using data from past observations, and based of them make precise prediction

In [6]:
import numpy

#creating 1d array (vector)
vector = numpy.array([1,2,3],dtype=numpy.int8)
print(f"vector's dimension:{vector.ndim} \n")
#creating 2d array (matrix)
matrix = numpy.array([ [1,2],[3,4] ])
print(f"matrix's dimension:{matrix.ndim} \n")
#creating 3d array
array3d  = numpy.array([ [ [1,2] ], [ [3,4] ], [ [5,6] ]])
print(f"array's shape {array3d.shape}")

array1 = numpy.arange(1,10) # 1,2,3,4,5 .. 10
array2 = numpy.arange(1,10,2) # 1 , 3, 5 .. 9
array3 = numpy.linspace(0,1,0.1,dtype=numpy.float16) #0.0, 0.1, 0.2 .. 1.0


vector's dimension:1 

matrix's dimension:2 

array's shape (3, 1, 2)


In [11]:
#numpy provide functionality changing values while slicing an array
slice1 = numpy.arange(99)
slice1[::2] = 99
print(slice1[4])

99


In [24]:
#numpy provide a option to resharp array to another dimensions
base = numpy.arange(20)
print(base.shape)
matrix4x5 = base.reshape((4,5))
print(matrix4x5.shape)
#pick column
print(matrix4x5[:,0])
#pick row
print(matrix4x5[0,:])
#pick all excepts the last column
print(matrix4x5[:,:-1])
multiTable3 = numpy.arange(3**3)
multiTable3 = multiTable3.reshape((3,3,3))
#pick first elements of axis 0
print(multiTable3[0, :, 0])

(20,)
(4, 5)
[ 0  5 10 15]
[0 1 2 3 4]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[0 3 6]


Other method for slicing is to create auxiliary variable that will contain elements that we want to slice. Positions which value will be True means that these ones are what we are interested in

In [26]:
full = numpy.arange(9).reshape((3,3))
positionsToSlice = numpy.array([[True, False, False],[True, False, False],[True, False, False]])
print(full[positionsToSlice])


[0 3 6]


CHEATSHEET LINK:

https://blog.finxter.com/numpy-cheat-sheet/